roles:
  - src: https://github.com/digimokan/ans_role_config_automatic_printing
  - src: https://github.com/digimokan/ans_role_config_automatic_scanning
  - src: https://github.com/digimokan/ans_role_config_avahi
  - src: https://github.com/digimokan/ans_role_config_bitwarden_cli
  - src: https://github.com/digimokan/ans_role_config_chromium
  - src: https://github.com/digimokan/ans_role_config_cron
  - src: https://github.com/digimokan/ans_role_config_firefox
  - src: https://github.com/digimokan/ans_role_config_freebsd_linux_compat
  - src: https://github.com/digimokan/ans_role_config_fish
  - src: https://github.com/digimokan/ans_role_config_fonts
  - src: https://github.com/digimokan/ans_role_config_freebsd_ports
  - src: https://github.com/digimokan/ans_role_config_fzf
  - src: https://github.com/digimokan/ans_role_config_group
  - src: https://github.com/digimokan/ans_role_config_hostname
  - src: https://github.com/digimokan/ans_role_config_jq
  - src: https://github.com/digimokan/ans_role_config_libreoffice
  - src: https://github.com/digimokan/ans_role_config_lightdm_dm
  - src: https://github.com/digimokan/ans_role_config_loader
  - src: https://github.com/digimokan/ans_role_config_lsblk
  - src: https://github.com/digimokan/ans_role_config_mate_de
  - src: https://github.com/digimokan/ans_role_config_obs
  - src: https://github.com/digimokan/ans_role_config_oss
  - src: https://github.com/digimokan/ans_role_config_passlib
  - src: https://github.com/digimokan/ans_role_config_restic
  - src: https://github.com/digimokan/ans_role_config_security_hardening
  - src: https://github.com/digimokan/ans_role_config_shell
  - src: https://github.com/digimokan/ans_role_config_simple_scan
  - src: https://github.com/digimokan/ans_role_config_sndio
  - src: https://github.com/digimokan/ans_role_config_sudo
  - src: https://github.com/digimokan/ans_role_config_time
  - src: https://github.com/digimokan/ans_role_config_upgrades
  - src: https://github.com/digimokan/ans_role_config_user
  - src: https://github.com/digimokan/ans_role_config_user_playbook
  - src: https://github.com/digimokan/ans_role_config_video_drivers
  - src: https://github.com/digimokan/ans_role_config_vlc
  - src: https://github.com/digimokan/ans_role_config_webcam
  - src: https://github.com/digimokan/ans_role_config_xdg_user_dirs
  - src: https://github.com/digimokan/ans_role_config_xorg
  - src: https://github.com/digimokan/ans_role_config_xsel
  - src: https://github.com/digimokan/ans_role_config_zfs_datasets
  - src: https://github.com/digimokan/ans_role_config_zfs_hw
  - src: https://github.com/digimokan/ans_vars_browser_search_providers

