# vars.yml:
#   - has vars pointing to matching encrypted vars in vault.yml
#
# vault.yml:
#   - orig encrypt:   ansible-vault encrypt host_vars/vault.yml
#   - edit in place:  ansible-vault edit host_vars/vault.yml
#   - view read-only: ansible-vault view host_vars/vault.yml
#
# Notes:
#   - ansible-vault cmd uses vault password from vault_password.txt
#   - ansible-playbook cmd also uses vault password from vault_password.txt
#   - ansible.cfg wires up vault_password.txt
#   - playbook.yml wires up linking in vars from vars.yml, vault.yml

# main user-login/account-name on the workstation PC
wkst_user_and_group_name: "{{ vault_wkst_user_and_group_name }}"

# for config_restic: an S3 bucket that will host the remote-backup repo
wkst_user_restic_s3_bucket_url: "{{ vault_wkst_user_restic_s3_bucket_url }}"

# for config_restic: the storage-provider-issued ID for the S3 bucket
wkst_user_restic_s3_bucket_key_id: "{{ vault_wkst_user_restic_s3_bucket_key_id }}"

# for config_restic: the storage-provider-issued key-string for the S3 bucket
wkst_user_restic_s3_bucket_secret_keystring: "{{ vault_wkst_user_restic_s3_bucket_secret_keystring }}"

