# vault_clear.yml:
#   - has vars pointing to matching encrypted vars in vault_enc.yml
#
# vault_enc.yml:
#   - orig encrypt:   ansible-vault encrypt host_vars/vault_enc.yml
#   - edit in place:  ansible-vault edit host_vars/vault_enc.yml
#   - view read-only: ansible-vault view host_vars/vault_enc.yml
#
# Notes:
#   - ansible-vault cmd uses vault password from vault_password.txt
#   - ansible-playbook cmd also uses vault password from vault_password.txt
#   - ansible.cfg wires up vault_password.txt
#   - playbook.yml wires up linking in vars from vault_enc.yml, vault_clear.yml

# main user-login/account-name on the workstation PC
vault_clear_wkst_user_and_group_name: "{{ vault_enc_wkst_user_and_group_name }}"

# for config_restic: an S3 bucket that will host the remote-backup repo
vault_clear_restic_s3_bucket_url: "{{ vault_enc_restic_s3_bucket_url }}"

# for config_restic: the storage-provider-issued ID for the S3 bucket
vault_clear_restic_s3_bucket_key_id: "{{ vault_enc_restic_s3_bucket_key_id }}"

# for config_restic: the storage-provider-issued key-string for the S3 bucket
vault_clear_restic_s3_bucket_secret_keystring: "{{ vault_enc_restic_s3_bucket_secret_keystring }}"

